export const servicesList = [
    { id: 1, name: "Agricultural Land Value Application" },
    { id: 2, name: "Agriculture Income Certificate" },
    { id: 3, name: "Apathbandhu Scheme" },
    { id: 4, name: "Appeals on Demarcation" },
    { id: 5, name: "CC of ROM HYD" },
    { id: 6, name: "Certified Copies of TSLR" },
    { id: 7, name: "Change of Name Application" },
    { id: 8, name: "Community and Date of Birth Certificate" },
    { id: 9, name: "Cracker or Storage of Explosive Material License" },
    { id: 10, name: "Demarcation HYD" },
    { id: 11, name: "EBC Certificate" },
    { id: 12, name: "Economically weaker Section" },
    { id: 13, name: "Extract of House Site Patta Extract of Dform Patta" },
    { id: 14, name: "Extract of NOC Under Explosive Petroleum Act" },
    { id: 15, name: "Extract of ORC" },
    { id: 16, name: "Family Membership Certificate" },
    { id: 17, name: "Fline Petitions Sub Division" },
    { id: 18, name: "Gap Certificate" },
    { id: 19, name: "Income Certificate" },
    { id: 20, name: "Issue of Arm Licence" },
    { id: 21, name: "Issue of Caste Certificate to Brahmin Community" },
    { id: 22, name: "Issue of NOC for Storing of Petroleum Products" },
    { id: 23, name: "Issue of Occupancy Rights Cert for Inam Lands" },
    { id: 24, name: "Issue of Small and Marginal Farmer Certificate" },
    { id: 25, name: "Issue of Tonch Map" },
    { id: 26, name: "Late Registration of Birth Death" },
    { id: 27, name: "Local Candidate Certificate for Educational Institutional Purpose" },
    { id: 28, name: "Localization of Properties HYD" },
    { id: 29, name: "Minority Certificate" },
    { id: 30, name: "Money Lending" },
    { id: 31, name: "Nativity Certificate" },
    { id: 32, name: "NFBS Application" },
    { id: 33, name: "No Earning Member Certificate" },
    { id: 34, name: "No Objection Certificate" },
    { id: 35, name: "No Property Application Service" },
    { id: 36, name: "NOC for Construction of Cinema Hall" },
    { id: 37, name: "OBC Certificate" },
    { id: 38, name: "Orphanage Integrated Certificate Application" },
    { id: 39, name: "Pawn Broker" },
    { id: 40, name: "Permission for Digging an Agricultural Well / Drinking Water Well" },
    { id: 41, name: "Permission to Run the Benefit Show" },
    { id: 42, name: "Possession Certificate" },
    { id: 43, name: "Refund of Trade Deposit" },
    { id: 44, name: "Renewal of Cinema Licence" },
    { id: 45, name: "Residence Certificate" },
    { id: 46, name: "Village Map Copy" }
  ];
  